### PR TITLE
Volume Profiles extension

### PR DESCRIPTION
**Pull request by notPlancha**
Hey gals! I wanted to share a spicetify extension I was working on: Volume Profiles! Let me know what you think and all of that. I'm opting to host it on my page, but I'm sure that's not an issue. If you have any questions drop them!

### CODE REVIEW

**Review by 3raxton — COMMENTED** [review]
Hey, @notPlancha, happy to have you as (almost) part of the repo! Would you mind changing the line `Same thing for any other issue/bug` in the notes section clearer? If potential users skim your README, they may end up opening an issue in this repo. 

If you could change the language to ensure that an issue needs to be opened on your repo, that would be great. Looking forward to merging this PR once changes are made 🔥

**Comment by 3raxton** [comment]
Also, does Volume Profiles support the new version of Spotify?

**Comment by notPlancha** [comment]
About the line, I changed it feel free to critique it. 
About the new version, this extension was only tested in the most recent version of both spotify (1.1.59.714.g7e040462-a) and spicetify (2.2.2), but it should work for old versions and future ones.

**Comment by 3raxton** [comment]
Looks great, I'm a big fan of the new line, it's easy to understand and directs people to the right area. 

Feel free to add your name to AUTHORS.md file, you're merged! 🔥

**Pull request merged**
