### PR TITLE
Update auto skip sad songs

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
For this PR, I just fixed the image path for the readme and I also added the gui from the screenshot to make the app more usable. I just wanted to add a comment in case the pr open notification got lost. On an unrelated note, I have been trying to make a song statistics recorder but I can't find a good way to access the data outside of the app.

**Comment by einzigartigerName** [comment]
You can have an extension running a client which sends the relevant data to a server run by the statistics recorder app.

**Comment by JakeRoggenbuck** [comment]
Oh, I'll try that, thanks so much!

**Comment by 3raxton** [comment]
Sorry about the delay here. Is there anything further you'd like to add to the commit @JakeRoggenbuck in terms of a statistics recorder? If not, or if you want me to keep the PR open, let me know. Otherwise, I'll merge

**Comment by JakeRoggenbuck** [comment]
@3raxton No worries, this PR is ready for a merge. The statistics idea might be another extension made sometime in the future. Thanks!

**Comment by 3raxton** [comment]
Good stuff @JakeRoggenbuck, it's merged! 🔥

**Pull request merged**
